checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - tests/*

tools:
    external_code_coverage: true
    php_mess_detector: true
    sensiolabs_security_checker: true
    php_cs_fixer: true
    php_code_sniffer: true

