checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - tests/*

tools:
    external_code_coverage: true
    php_code_sniffer:
        config:
            standard: "PSR2"

